name: flutter_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  get_storage: ^2.0.2

dev_dependencies:
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
